# https://gohugo.io/getting-started/configuration/

title: 민주노총사진아카이브
baseURL: https://kctu-photo.durumi.io
languageCode: ko-kr
hasCJKLanguage: true
paginate: 60
defaultContentLanguage: ko

theme:
  - github.com/team-durumi/tailwind-aa-theme
  - github.com/team-durumi/hugo-search-fuse-js-aa

build:
  writeStats: true

taxonomies:
  tag: tags
  subject: subjects
  creator: creators
  venue: venues
  event: events
  culture_worker: culture_workers
  issue: issues
