# https://gohugo.io/getting-started/configuration/

title: 민주노총사진아카이브
baseURL: https://compassionate-mayer-7c07b1.netlify.app
languageCode: ko-kr
hasCJKLanguage: true

theme:
  github.com/team-durumi/tailwind-aa-theme

build:
  writeStats: true

taxonomies:
  tag: tags
  subject: subjects
  creator: creators
  venue: venues
  event: events
