main:
  - name: 사진 찾아보기
    url: /search/
    weight: -70
  - name: 전체사진 보기
    url: /items/
    weight: -100
  - name: 사진 컬렉션
    url: 
    weight: -90
  - name: 주제 분류
    url: subjects
    weight: 1
    parent: 사진 컬렉션
  - name: 조직 분류
    url: creators
    weight: 2
    parent: 사진 컬렉션
  - name: 장소 분류
    url: venues
    weight: 3
    parent: 사진 컬렉션
  - name: 행사 분류
    url: events
    weight: 4
    parent: 사진 컬렉션
  - name: 사건 분류
    url: issues
    weight: 5
    parent: 사진 컬렉션
  - name: 오늘의사진
    url: /exhibitions/
    weight: -80

footer:
  - name: 소개
    url: /
    weight: -100
  - name: 공지사항
    url: posts
    weight: 1
    parent: 소개 
  - name: 오늘의 사진
    url: exhibitions
    weight: 2
    parent: 소개
  - name: 자료
    url:
    weight: -90
  - name: 전체사진 보기
    url: items
    weight: 1
    parent: 자료
  - name: 사진 찾아보기
    url: search
    weight: 2
    parent: 자료
  - name: 사진 컬렉션
    url: 
    weight: -80
  - name: 주제 분류
    url: subjects
    weight: 1
    parent: 사진 컬렉션
  - name: 조직 분류
    url: creators
    weight: 2
    parent: 사진 컬렉션
  - name: 장소 분류
    url: venues
    weight: 3
    parent: 사진 컬렉션
  - name: 행사 분류
    url: events
    weight: 4
    parent: 사진 컬렉션
  - name: 사건 분류
    url: issues
    weight: 5
    parent: 사진 컬렉션
  - name: 운영 및 협력
    url: 
    weight: -70
  - name: 민주노총
    url: https://nodong.org
    weight: 1
    parent: 운영 및 협력
  - name: 노동과세계
    url: http://worknworld.kctu.org
    weight: 2
    parent: 운영 및 협력