main:
  - name: 검색
    url: /search/
    weight: -90  
  - name: 탐색
    url: /items/
    weight: -100
  - name: 컬렉션
    url: /collection-list/
    weight: -80
  - name: 전시
    url: /exhibitions/
    weight: -70
  - name: 오늘의 사진
    url: /exhibitions/
    weight: -60    