title: 민주노총사진아카이브
description: 생산의 주역이며 사회개혁과 역사발전의 원동력인 우리들 노동자는 오늘 자주적이고 민주적인 노동조합의 전국중앙조직, 전국민주노동조합총연맹의 창립을 선언한다. 이 사이트는 민주노총의 사진아카이브입니다.
images:
  - site-feature-image.jpg

cfImagePrefix: 'https://kctu-photo.durumi.io/cdn-cgi/image'
cfImageStyles:
  thumb: 'fit=scale-down,width=300'
  full: 'fit=scale-down,width=1920'