title: 민주노총사진아카이브
description: 노동과세계에 보도된 사진을 중심으로 민주노총 26년 역사를 정리하고 있습니다.
images:
  - site-feature-image.jpg

cfImagePrefix: 'https://kctu-photo.durumi.io/cdn-cgi/image'
cfImageStyles:
  thumb: 'fit=scale-down,width=300'
  full: 'fit=scale-down,width=1920'
  frontSlide: 'fit=cover,width=1920,height=1280'
  thumb2by3: 'fit=cover,width=300,height=200'

image_extension_whitelist:
  - jpg
  - jpeg
  - png
  - gif
  - JPG
