ignoreFiles:
  - "items/2020년/1월/.*"
  - "items/2020년/2월/.*"
  - "items/2020년/3월/.*"
  - "items/2020년/4월/.*"
  - "items/2020년/5월/.*"
  - "items/2020년/6월/.*"
  - "items/2020년/7월/.*"
  - "items/2020년/8월/.*"
  - "items/2020년/9월/.*"
  - "items/2020년/10월/.*"
  - "items/2020년/11월/.*"
  - "items/2021년/3월/.*"
  - "items/2021년/4월/.*"
  - "items/2021년/5월/.*"
  - "items/2021년/6월/.*"
  - "items/2021년/7월/.*"
  - "items/2021년/8월/.*"
  - "items/2021년/9월/.*"
  - "items/2021년/10월/.*"
  - "items/2021년/11월/.*"
