
ignoreFiles:
  - "items/2021년/3월/.*"
  - "items/2021년/4월/.*"
  - "items/2021년/5월/.*"
  - "items/2021년/6월/.*"
  - "items/2021년/7월/.*"
  - "items/2021년/8월/.*"
  - "items/2021년/9월/.*"
  - "items/2021년/10월/.*"
  - "items/2021년/11월/.*"